import { mkdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import * as path from "node:path";
import * as readline from "node:readline";
import * as fs from "node:fs";
import { readManifest } from "../../../core/manifest.js";
import { loadNodeIdentity } from "../../../core/node.js";
import { loadWorkflowPolicy } from "../../../governance/workflow-policy.js";
import { getTraceFilePath } from "../../../core/trace-writer.js";
import { writeCanonicalTraceRecord } from "../../../trace/writer.js";
import { readTruthRuntimeSnapshot } from "../../../core/truth-runtime.js";

const ROOT_DIR = process.cwd();
const CONTEXT_DIR = path.join(ROOT_DIR, ".z-mos", "context");
const CONTEXT_FILE = path.join(CONTEXT_DIR, "workspace.md");
const RECENT_TRACE_LIMIT = 10;

type TraceEntry = {
  timestamp?: string;
  command?: string;
  execution_status?: string;
  result_class?: string;
  details?: Record<string, unknown>;
};

async function readRecentTraceEntries(): Promise<TraceEntry[]> {
  const tracePath = await getTraceFilePath();
  if (!existsSync(tracePath)) return [];

  const entries: TraceEntry[] = [];
  const stream = fs.createReadStream(tracePath, { encoding: "utf8" });
  const rl = readline.createInterface({ input: stream, crlfDelay: Infinity });

  for await (const line of rl) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    try {
      entries.push(JSON.parse(trimmed) as TraceEntry);
    } catch {
      // skip malformed lines
    }
  }

  return entries.slice(-RECENT_TRACE_LIMIT);
}

async function readTopLevelDirs(): Promise<string[]> {
  try {
    const { readdir } = await import("node:fs/promises");
    const entries = await readdir(ROOT_DIR, { withFileTypes: true });
    return entries
      .filter((e) => e.isDirectory() && !e.name.startsWith(".") && e.name !== "node_modules" && e.name !== "dist")
      .map((e) => e.name)
      .sort();
  } catch {
    return [];
  }
}

function formatTraceEntries(entries: TraceEntry[]): string {
  if (entries.length === 0) return "  (no recent trace entries)";
  return entries
    .map((e) => {
      const ts = e.timestamp ? e.timestamp.slice(0, 19) : "unknown";
      const cmd = e.command ?? "unknown";
      const status = e.execution_status ?? "unknown";
      const cls = e.result_class ?? "unknown";
      return `  - [${ts}] ${cmd} → ${status} (${cls})`;
    })
    .join("\n");
}

export async function runContextBuildCommand(args: string[] = []): Promise<void> {

  if (args.includes("--mode=minimal") || args.find(a => a.startsWith("--mode=minimal"))) {
    let projectState: any = {};
    let intentCard: any = {};
    try {
      projectState = JSON.parse(await readFile(path.join(ROOT_DIR, ".z-mos/state/project-state.json"), "utf8"));
    } catch {}
    try {
      intentCard = JSON.parse(await readFile(path.join(ROOT_DIR, ".z-mos/intent.card.json"), "utf8"));
    } catch {}
    
    const payload = {
      current_phase: projectState.current_phase || "unknown",
      active_gate: projectState.active_gate || "standard",
      active_stream: projectState.active_stream || null,
      next_safe_action: intentCard?.human?.intent || projectState.next_safe_action || "unknown",
      blocker: projectState.current_working_blocker || "none",
      resume_mode: "truth_first",
      latest_evidence_refs: [],
      latest_artifact_paths: [".z-mos/reports/latest.json"]
    };
    
    console.log(JSON.stringify(payload, null, 2));
    return;
  }

  const [manifest, truthRuntime, nodeIdentity, workflowPolicy, recentTrace, topLevelDirs] =
    await Promise.all([
      readManifest(),
      readTruthRuntimeSnapshot(),
      loadNodeIdentity(),
      loadWorkflowPolicy(),
      readRecentTraceEntries(),
      readTopLevelDirs(),
    ]);

  const now = new Date().toISOString();

  const lines: string[] = [
    `# Z-MOS Workspace Context`,
    ``,
    `> Generated by \`zcl ai context build\` at ${now}`,
    `> This file is machine-generated. Do not edit manually.`,
    ``,
    `## Repository`,
    ``,
    `- **Name:** ${manifest.repository.name}`,
    `- **Framework:** ${manifest.repository.framework}`,
    `- **Version:** ${manifest.repository.version}`,
    ``,
    `## Runtime`,
    ``,
    `- **Platform:** ${manifest.runtime.platform}`,
    `- **Module System:** ${manifest.runtime.moduleSystem}`,
    `- **Entry Command:** ${manifest.runtime.entryCommand}`,
    ``,
    `## Governance Status`,
    ``,
    `- **Stage:** ${manifest.status.stage}`,
    `- **AI CLI:** ${manifest.status.aiCli}`,
    `- **Lifecycle:** ${manifest.lifecycle.status}`,
    `- **Last Updated:** ${manifest.lifecycle.updatedAt}`,
    `- **Reason:** ${manifest.lifecycle.reason}`,
    ``,
    `## Session`,
    ``,
    `- **Session State:** ${truthRuntime.sessionState}`,
    `- **Active Command:** truth-first`,
    ``,
    `## Node Identity`,
    ``,
    `- **Node ID:** ${nodeIdentity.node_id}`,
    `- **Node Role:** ${nodeIdentity.node_role}`,
    ``,
    `## Workflow Policy`,
    ``,
    ...workflowPolicy.workflows.map((w) =>
      [
        `### ${w.workflowName}`,
        `- Advisory AI Allowed: ${w.advisoryAiAllowed}`,
        `- Mutation Allowed: ${w.mutationAllowed}`,
        `- Delegation Allowed: ${w.delegationAllowed}`,
        w.allowedTasks ? `- Allowed Tasks: ${w.allowedTasks.join(", ")}` : null,
        ``,
      ]
        .filter((l): l is string => l !== null)
        .join("\n"),
    ),
    `## Workspace Structure`,
    ``,
    `Top-level directories (excluding hidden and dist/node_modules):`,
    ``,
    ...topLevelDirs.map((d) => `- \`${d}/\``),
    ``,
    `## Mutation Scope`,
    ``,
    `- **Mode:** ${manifest.scope.mutation.mode}`,
    `- **Allowed Paths:** ${manifest.scope.mutation.allowedPaths.join(", ")}`,
    `- **Protected Paths:** ${manifest.scope.mutation.protectedPaths.join(", ")}`,
    ``,
    `## Recent Trace (last ${RECENT_TRACE_LIMIT} entries)`,
    ``,
    formatTraceEntries(recentTrace),
    ``,
  ];

  const content = lines.join("\n");

  await mkdir(CONTEXT_DIR, { recursive: true });
  await writeFile(CONTEXT_FILE, content, "utf8");

  const relativePath = path.relative(ROOT_DIR, CONTEXT_FILE);
  console.log(`CONTEXT_BUILD: workspace context written to ${relativePath}`);
  console.log(`  repository=${manifest.repository.name}, version=${manifest.repository.version}`);
  console.log(`  workflows=${workflowPolicy.workflows.length}, trace_entries=${recentTrace.length}`);

  const traceResult = await writeCanonicalTraceRecord({
    command: "zcl ai context build",
    actor: "system",
    execution_status: "success",
    result_class: "success",
    preflight_status: "not-evaluated",
    canonical_status: "healthy",
    policy_status: "not-applicable",
    trace_expectation: "required-if-business-logic",
    trace_result: "emitted",
    details: {
      contextPath: relativePath,
      workflowCount: workflowPolicy.workflows.length,
      recentTraceEntries: recentTrace.length,
      topLevelDirs,
    },
  });

  if (!traceResult.ok) {
    console.warn(`TRACE_WARN: trace write failed — ${traceResult.error}`);
  }
}
