export class TrustEnvelopeValidationError extends Error {
  readonly code: string;

  constructor(code: string, message: string) {
    super(`[${code}] ${message}`);
    this.code = code;
  }
}

export const TRUST_ENVELOPE_ERROR_CODES = {
  HIDDEN_AUTHORITY: "HIDDEN_AUTHORITY",
  EMPTY_AUTHORITY_OWNER: "EMPTY_AUTHORITY_OWNER",
  MISSING_ISSUER_AUTHORITY: "MISSING_ISSUER_AUTHORITY",
  INVALID_DELEGATION_CHAIN: "INVALID_DELEGATION_CHAIN",
  SELF_AUTHORIZED_ESCALATION: "SELF_AUTHORIZED_ESCALATION",
  INVALID_LIFECYCLE_STATE: "INVALID_LIFECYCLE_STATE",
  STALE_ENVELOPE: "STALE_ENVELOPE",
  MISSING_VERIFICATION_POLICY: "MISSING_VERIFICATION_POLICY",
  INVALID_FEDERATION_SCOPE: "INVALID_FEDERATION_SCOPE",
  INVALID_ACCEPTED_TRUTH_LINEAGE_REFERENCE: "INVALID_ACCEPTED_TRUTH_LINEAGE_REFERENCE",
  MALFORMED_TRUST_REFERENCE: "MALFORMED_TRUST_REFERENCE",
  INVALID_SIGNATURE_METADATA: "INVALID_SIGNATURE_METADATA",
} as const;
