export class MembershipTransitionValidationError extends Error {
  readonly code: string;

  constructor(code: string, message: string) {
    super(`[${code}] ${message}`);
    this.code = code;
  }
}

export const MEMBERSHIP_TRANSITION_ERROR_CODES = {
  UNKNOWN_CURRENT_STATE: "UNKNOWN_CURRENT_STATE",
  UNKNOWN_TARGET_STATE: "UNKNOWN_TARGET_STATE",
  INVALID_TRANSITION: "INVALID_TRANSITION",
  MISSING_AUTHORITY_APPROVAL: "MISSING_AUTHORITY_APPROVAL",
  MISSING_EVIDENCE_REFERENCE: "MISSING_EVIDENCE_REFERENCE",
  INVALID_RECOVERY_PATH: "INVALID_RECOVERY_PATH",
  SCOPE_ESCALATION_WITHOUT_APPROVAL: "SCOPE_ESCALATION_WITHOUT_APPROVAL",
  STALE_MEMBERSHIP_STATE: "STALE_MEMBERSHIP_STATE",
  MALFORMED_MEMBERSHIP_REFERENCE: "MALFORMED_MEMBERSHIP_REFERENCE",
} as const;
