export class LocalKernelValidationError extends Error {
  readonly code: string;

  constructor(code: string, message: string) {
    super(`[${code}] ${message}`);
    this.code = code;
  }
}

export const LOCAL_KERNEL_ERROR_CODES = {
  MALFORMED_INTENT: "MALFORMED_INTENT",
  MISSING_SUBJECT_REF: "MISSING_SUBJECT_REF",
  MISSING_ISSUER_REF: "MISSING_ISSUER_REF",
  MISSING_HUMAN_AUTHORIZATION: "MISSING_HUMAN_AUTHORIZATION",
  MISSING_TRUST_ENVELOPE_REF: "MISSING_TRUST_ENVELOPE_REF",
  TRUST_ENVELOPE_MISSING: "TRUST_ENVELOPE_MISSING",
  TRUST_ENVELOPE_INVALID: "TRUST_ENVELOPE_INVALID",
  TRUST_ENVELOPE_REF_MISMATCH: "TRUST_ENVELOPE_REF_MISMATCH",
  TRUST_SCOPE_VIOLATION: "TRUST_SCOPE_VIOLATION",
  INVALID_ACTION_SCOPE: "INVALID_ACTION_SCOPE",
  AMBIGUOUS_VERIFICATION: "AMBIGUOUS_VERIFICATION",
  TRACE_APPEND_FAILURE: "TRACE_APPEND_FAILURE",
  REPLAY_INVALID_SEQUENCE: "REPLAY_INVALID_SEQUENCE",
  REPLAY_DUPLICATE_SEQUENCE: "REPLAY_DUPLICATE_SEQUENCE",
  REPLAY_SEQUENCE_GAP: "REPLAY_SEQUENCE_GAP",
  REPLAY_MALFORMED_RECORD: "REPLAY_MALFORMED_RECORD",
  REPLAY_UNKNOWN_DECISION_STATUS: "REPLAY_UNKNOWN_DECISION_STATUS",
  REPLAY_SUMMARY_FAILURE: "REPLAY_SUMMARY_FAILURE",
  EVIDENCE_REPLAY_FAILED: "EVIDENCE_REPLAY_FAILED",
  EVIDENCE_COUNT_MISMATCH: "EVIDENCE_COUNT_MISMATCH",
  EVIDENCE_DECISION_ID_MISMATCH: "EVIDENCE_DECISION_ID_MISMATCH",
  EVIDENCE_INTENT_ID_MISMATCH: "EVIDENCE_INTENT_ID_MISMATCH",
  EVIDENCE_MALFORMED_INPUT: "EVIDENCE_MALFORMED_INPUT",
  EVIDENCE_SUMMARY_FAILURE: "EVIDENCE_SUMMARY_FAILURE",
  TRACE_PERSISTENCE_WRITE_FAILED: "TRACE_PERSISTENCE_WRITE_FAILED",
  TRACE_PERSISTENCE_READ_FAILED: "TRACE_PERSISTENCE_READ_FAILED",
  TRACE_PERSISTENCE_MALFORMED_RECORD: "TRACE_PERSISTENCE_MALFORMED_RECORD",
  TRACE_PERSISTENCE_MALFORMED_JSON: "TRACE_PERSISTENCE_MALFORMED_JSON",
  TRACE_PERSISTENCE_INVALID_PATH: "TRACE_PERSISTENCE_INVALID_PATH",
  RECOVERY_REPLAY_FAILED: "RECOVERY_REPLAY_FAILED",
  RECOVERY_EVIDENCE_INCOMPLETE: "RECOVERY_EVIDENCE_INCOMPLETE",
  RECOVERY_EVIDENCE_FAILED: "RECOVERY_EVIDENCE_FAILED",
  RECOVERY_TRACE_SEQUENCE_INVALID: "RECOVERY_TRACE_SEQUENCE_INVALID",
  RECOVERY_TRACE_MALFORMED: "RECOVERY_TRACE_MALFORMED",
  RECOVERY_INPUT_MISSING: "RECOVERY_INPUT_MISSING",
  RECOVERY_REPAIR_PROHIBITED: "RECOVERY_REPAIR_PROHIBITED",
  RECOVERY_SUMMARY_FAILURE: "RECOVERY_SUMMARY_FAILURE",
} as const;
