import { promises as fs } from "node:fs";
import * as path from "node:path";
import { execSync } from "node:child_process";

export async function runHooksInstallCommand(): Promise<void> {
  const rootDir = process.cwd();
  const hooksDir = path.join(rootDir, ".git", "hooks");
  const preCommitPath = path.join(hooksDir, "pre-commit");

  const hookContent = `#!/bin/sh
# Z-MOS pre-commit hook template
# Auto-generated by zcl hooks install

echo "[Z-MOS] Running preliminary worktree verification..."
npm run ops:preflight
if [ $? -ne 0 ]; then
  echo "[Z-MOS] Preflight blocked the commit. Please fix blockers and try again."
  exit 1
fi
exit 0
`;

  try {
    await fs.mkdir(hooksDir, { recursive: true });
    
    let exists = false;
    try {
      await fs.access(preCommitPath);
      exists = true;
    } catch {}

    if (exists) {
      console.log(`[INFO] pre-commit hook already exists at ${preCommitPath}`);
      console.log("No changes made. Consider adding 'npm run ops:preflight' manually.");
      return;
    }

    await fs.writeFile(preCommitPath, hookContent, { mode: 0o755 });
    console.log(`[PASS] Successfully installed lightweight pre-commit hook at ${preCommitPath}`);
  } catch (err: any) {
    console.error(`[FAIL] Failed to install pre-commit hook: ${err.message}`);
    process.exitCode = 1;
  }
}
